[gee_service_account]
email = "satwik-sunnam@geosi-445300.iam.gserviceaccount.com"
key = '''-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDpN8nFXbyxU5Qc
gTckkrQCyue2Lx0ysr8jgGh3Uxquc0IXa4jETEKFWGwYOXtWdSu7QxMcIlFm5PQN
CLB9uvF328fxdKaRqDmAxvR9akt/QgSAUVDjkc17Jlo6rftiN6Q8LGZ2nRgDntil
hGCaConc/JOMxu2WpBADj9Ls++PAIc0WpSnjMfrPbWT9HwFUsn90a/ab7Al8FEYy
T6bu0qqDaWO/vkA4rIXHGibCWDjLovXWX27mMOXJpmej38SKKK2dSKXv6jJvbl9p
mPzvGhGjbPeCBE+EXQZZmFUsLIbHYMSi5InooYQgfFupd90H45Q0Ohfj7630pwuM
qNudeNJBAgMBAAECggEAKsUBIwmbgO6pryeQSAwCaK+y2kGeKm3G6VkTb2ylbEA1
auuc35j3qxIp8rBZ+uNOk49LuiFeCc9rpVdGXKxzu44qBxEkOfqenwv9iuF7OnmO
L0UaXz2eMBs6uV+uRhcbrrBa0x5gqMtRAlu6Ro2vtj/4xDy4FiP8ztZpsW3JWPLQ
UsiLZraoQtP/17KqmiLg6PR2FWpEXU9MyOuSVXCg8yPSz+yk2Z5AEuCGQHHTcxFq
vSuvW3RSv/RdnmKVqX7w+TFqSIMRBRd0gdoAT7Be2Ww/hT+IqkdxCEhl0i7qnjlk
Zh1WwzsMI6TJQQqGzewLzGGJs5BVYtZb4i003Bn9xQKBgQD4HX/riEbI/cLqv0rC
wPeRw245cpiiOCT5zCuYrYLFsuL45HZByI/CS6cderbIEGZax8cbjmuXX9HGh3As
YkIrTOl+MH6OHiIv+xS7GNL/TtBs3K6iTVhX4p/EQNsScFBQr4sIqGkmdQWkSlYz
o8U2KhwKgazObgvMwxmiEw35rQKBgQDwoRgImrNTOnu3BbgfOkPa2YXIEdcgqiqK
4iGqJ8C4986kPoj61oVXv8naPp/W/AuEvO6ncXGwR/40mm/3UqGm5jWT/EngEk2g
Uh4/bRKiqKNb2uMduylagtjkBQcReRBzR4yK3Gw+tMHpuSksWah89//21edeg1j9
+HR3Pua1ZQJ/FkqQM5kKwwQJfw2wqc6sb2wfewnQrMJekBLH1+++0ARCYBomhcJ/
J/WkDgH4agEPMRjByrgA8pipQCzq5xHs3/cJA01YEWyjpavpMOYKDuYF08H/7pUE
WuEBeaBaDk4I6TbcRurah5n758bF992+2h7uZgNAg0tfxAXDR8xudQKBgFmgBu2d
gVFspQvEa5HmB8QJ5RRh4Ljf6LyWAWf5KoU6d5MhX6/eGwhV/P72+F4AvuGP5Wwk
iu3Xws0hALcj5eXeNPKLs5BsANHIBFAndhtzqHTcEF/QiFSYC+TSIpHVf9UQPz6x
Xvf0J43AU5+bPXBehs4PWgAP+COQWQDZQuEpAoGBAJ42TDJvmKiBHAuiF8RSkGit
3lSKNRRWAQ1RCwufNfc/wDr1YOpJWgHw6y1D4JTc2o1cF+BDffPxh+ldpNJpY6hA
rD8MzCyhujHPl5EedVVsgVrA/FZ9Y4VcTokCNslxsaJj8TtYJDQE3msl+MVuq7RZ
ctgMo87RfoOVQc13XjNn
-----END PRIVATE KEY-----'''

[gee]
project_id = "geosi-445300"
private_key_id = "e69b40ae1962c2f0537fecb6841961ed41f62b33"
client_id = "112204416338150971367"